version: "2"
run:
  go: "1.24"
  modules-download-mode: vendor
  issues-exit-code: 1
  tests: true
  allow-parallel-runners: false
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - durationcheck
    - errcheck
    - errorlint
    - gocheckcompilerdirectives
    - gocritic
    - godox
    - gosec
    - govet
    - ineffassign
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nilnil
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - staticcheck
    - tagalign
    - thelper
    - unconvert
    - unparam
    - unused
    - wastedassign
    - zerologlint
  settings:
    asasalint:
      exclude:
        - Append
        - \.Wrapf
      use-builtin-exclusions: true
    errcheck:
      check-type-assertions: true
      check-blank: true
    errorlint:
      errorf: true
      errorf-multi: true
      asserts: true
      comparison: true
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - dupImport
        - uncheckedInlineErr
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gosec:
      excludes:
        - G602
    govet:
      settings:
        printf:
          funcs: null
    lll:
      line-length: 140
      tab-width: 2
    nakedret:
      max-func-lines: 30
    nilnil:
      checked-types:
        - ptr
        - func
        - iface
        - map
        - chan
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
    prealloc:
      simple: true
      range-loops: true
      for-loops: true
    predeclared:
      ignore:
        - new
        - int
      qualified-name: true
    promlinter:
      strict: true
      disabled-linters:
        - Help
        - Counter
        - HistogramSummaryReserved
        - MetricTypeInName
        - ReservedChars
        - CamelCase
        - UnitAbbreviations
    revive:
      confidence: 0.8
      severity: warning
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
        - name: unreachable-code
        - name: redefines-builtin-id
    rowserrcheck:
      packages:
        - github.com/jmoiron/sqlx
    tagalign:
      align: true
      sort: true
      order:
        - default
        - yaml
        - json
        - koanf
        - validate
      strict: true
    thelper:
      test:
        first: false
        name: false
        begin: false
      benchmark:
        first: false
        name: false
        begin: false
      tb:
        first: false
        name: false
        begin: false
    wsl:
      allow-trailing-comment: true
      allow-separated-leading-comment: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - funlen
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
severity:
  default: error
formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
