dictionaries = [
    "en_us",
    "en_gb",
    "ru",
]
words = [
    "DVCS",
    "Fpdf",
    "IDQR",
    "IIN",
    "badp",
    "bas",
    "bgddcp",
    "ccv",
    "clamd",
    "ddc",
    "eaddcp",
    "egdp",
    "egs",
    "eicar",
    "gopdfi",
    "nosec",
    "pdfcpu",
    "pdfcpuapi",
    "pdfcpumodel",
    "pdfcputypes",
    "rpcsrv",
    "БИН",
    "ИИН",
    "ЭЦП",
]
