name: Test and build
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    container: golangci/golangci-lint:latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config --global --add safe.directory '*'
          golangci-lint run -v ./...

  test:
    runs-on: ubuntu-latest
    container: golang:bookworm
    steps:
      - uses: actions/checkout@v4
      - run: |
          apt -qy update
          apt -qy install clamav clamav-daemon
          mkdir /var/run/clamav/
          chown clamav /var/run/clamav/
          /usr/bin/freshclam --foreground=true
          /usr/sbin/clamd -c /etc/clamav/clamd.conf
          sleep 3
          ls -la /var/run/clamav/
          ps aux
          cat /var/log/clamav/clamav.log
          CGO_ENABLED=0 go test -mod vendor -timeout 30m -count=1 -failfast ./... -v

  build:
    if: startsWith( github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    container: golang:bookworm
    steps:
      - uses: actions/checkout@v4
      - run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - run: |
          cd rpcsrv/cmd/
          CGO_ENABLED=0 go build -mod vendor -buildvcs=false -ldflags "-X 'main.BuildTimeStamp=$(date +%s)' -X 'main.AppVersion=${{ env.RELEASE_VERSION }}'" -o ddcrpcsrv .
          GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -mod vendor -buildvcs=false -ldflags "-X 'main.BuildTimeStamp=$(date +%s)' -X 'main.AppVersion=${{ env.RELEASE_VERSION }}'" -o ddcrpcsrv.exe .
          GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -mod vendor -buildvcs=false -ldflags "-X 'main.BuildTimeStamp=$(date +%s)' -X 'main.AppVersion=${{ env.RELEASE_VERSION }}'" -o ddcrpcsrv-darwin .
      - name: Archive rpcsrv builds
        uses: actions/upload-artifact@v4
        with:
          name: rpcsrv-build
          path: rpcsrv/cmd/ddcrpcsrv*
